spring:
  application:
    name: simple-spring-app-frontend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/university-site
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  thymeleaf:
    encoding: UTF-8

server:
  port: 8080
  servlet:
    context-path: /university

eureka:
  client:
    service-url:
      default-zone: ${EURECA_URI:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true
    fetch-registry: true
